# Generated by Django 5.1.1 on 2025-10-08 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Router',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=255)),
                ('img', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('удалено', 'Deleted'), ('действует', 'Exist')], default='действует', max_length=255)),
            ],
            options={
                'db_table': 'router',
            },
        ),
        migrations.CreateModel(
            name='ApplicationRouter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('черновик', 'Draft'), ('удалено', 'Deleted'), ('сформирован', 'Formulated'), ('завершён', 'Completed'), ('отклонён', 'Rejected')], default='черновик', max_length=255)),
                ('date_create', models.DateField()),
                ('date_modific', models.DateField(blank=True, null=True)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('Adress', models.CharField(max_length=255, null=True)),
                ('TotalUsers', models.IntegerField(blank=True, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications_created', to=settings.AUTH_USER_MODEL)),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applications_moderated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'applicationrouter',
            },
        ),
        migrations.CreateModel(
            name='AddedRouter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_router_id', models.IntegerField(blank=True, null=True)),
                ('router_load', models.CharField(blank=True, max_length=255, null=True)),
                ('id_application', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app.applicationrouter')),
                ('id_router', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app.router')),
            ],
            options={
                'db_table': 'addedrouter',
            },
        ),
    ]
