# Generated by Django 5.1.1 on 2025-09-24 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=255)),
                ('moderator', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(choices=[('черновик', 'Draft'), ('удалено', 'Deleted'), ('сформирован', 'Formulated'), ('завершён', 'Completed'), ('отклонён', 'Rejected')], default='черновик', max_length=255)),
                ('date_create', models.DateField()),
                ('date_modific', models.DateField(null=True)),
                ('date_end', models.DateField(null=True)),
                ('Adress', models.CharField(max_length=255, null=True)),
                ('TotalUsers', models.IntegerField()),
            ],
            options={
                'db_table': 'application',
            },
        ),
        migrations.CreateModel(
            name='Router',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=255)),
                ('img', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'router',
            },
        ),
        migrations.CreateModel(
            name='AddedRouter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_router_id', models.IntegerField()),
                ('router_load', models.CharField(max_length=255)),
                ('id_application', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app.application')),
                ('id_router', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app.router')),
            ],
            options={
                'db_table': 'addedrouter',
            },
        ),
    ]
