# Generated by Django 5.1.1 on 2025-09-24 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addedrouter',
            name='master_router_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='addedrouter',
            name='router_load',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
