# Generated by Django 5.1.1 on 2025-10-11 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addedrouter',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='applicationrouter',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='router',
            options={'managed': True},
        ),
    ]
