# Generated by Django 5.1.1 on 2025-09-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_addedrouter_master_router_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='TotalUsers',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
