# Generated by Django 5.1.1 on 2025-10-11 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_addedrouter_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addedrouter',
            options={},
        ),
        migrations.AlterModelOptions(
            name='applicationrouter',
            options={},
        ),
        migrations.AlterModelOptions(
            name='router',
            options={},
        ),
    ]
