# Generated by Django 5.2.7 on 2025-10-19 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_addedrouter_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addedrouter',
            name='router_load',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
