# Generated by Django 5.1.1 on 2025-10-06 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_application_totalusers'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationRouter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=255)),
                ('moderator', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('черновик', 'Draft'), ('удалено', 'Deleted'), ('сформирован', 'Formulated'), ('завершён', 'Completed'), ('отклонён', 'Rejected')], default='черновик', max_length=255)),
                ('date_create', models.DateField()),
                ('date_modific', models.DateField(blank=True, null=True)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('Adress', models.CharField(max_length=255, null=True)),
                ('TotalUsers', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'applicationrouter',
            },
        ),
        migrations.AlterField(
            model_name='router',
            name='status',
            field=models.CharField(choices=[('удалено', 'Deleted'), ('действует', 'Exist')], default='действует', max_length=255),
        ),
        migrations.AlterField(
            model_name='addedrouter',
            name='id_application',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app.applicationrouter'),
        ),
        migrations.DeleteModel(
            name='Application',
        ),
    ]
