# Generated by Django 5.1.1 on 2025-10-08 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_applicationrouter_alter_router_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationrouter',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='applications_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='applicationrouter',
            name='moderator',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applications_moderated', to=settings.AUTH_USER_MODEL),
        ),
    ]
